In [3]:
import numpy as np
import torch
import torch.nn as nn

In [19]:
l = nn.Linear(2,5)
v = torch.FloatTensor([1,2])
l(v)

tensor([-0.5825,  0.4272,  0.3845,  0.6221,  0.6407], grad_fn=<AddBackward0>)

In [20]:
s = nn.Sequential(
    nn.Linear(2,5),
    nn.ReLU(),
    nn.Linear(5,20),
    nn.ReLU(),
    nn.Linear(20,10),
    nn.ReLU(),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1)
)
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): ReLU()
  (6): Dropout(p=0.3)
  (7): Softmax()
)

In [21]:
s(torch.FloatTensor([[1,2]]))

tensor([[0.0907, 0.1801, 0.0861, 0.0861, 0.1148, 0.0861, 0.0976, 0.0861, 0.0861,
         0.0861]], grad_fn=<SoftmaxBackward>)

In [4]:
class OurModule(nn.Module):
    def __init__(self, num_inputs, num_classes, dropout_prob=0.3):
        super(OurModule, self).__init__()
        self.pipe = nn.Sequential(
            nn.Linear(num_inputs, 5),
            nn.ReLU(),
            nn.Linear(5, 20),
            nn.ReLU(),
            nn.Linear(20, num_classes),
            nn.Dropout(p=dropout_prob),
            nn.Softmax()
        )
        
    def forward(self, x):
        return self.pipe(x)

In [5]:
net = OurModule(num_inputs=2, num_classes=3)
v = torch.FloatTensor([[2,3]])
out = net(v)
print(net)
print(out)

OurModule(
  (pipe): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
    (5): Dropout(p=0.3)
    (6): Softmax()
  )
)
tensor([[0.3958, 0.1529, 0.4514]], grad_fn=<SoftmaxBackward>)


/home/zanion/.local/lib/python3.5/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
